services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=badges

pipeline:
  unit_testing:
    image: ruby:2.3
    environment:
      - DATABASE_DRIVER=postgres
      - DATABASE_CONFIG=postgres://postgres:mysecretpassword@127.0.0.1:5432/badges
    commands:
      # Install/Configure ImageMagick
      - apt update
      - apt install -y imagemagick mlocate
      - updatedb
      - wget http://www.imagemagick.org/Usage/scripts/imagick_type_gen
      - perl /drone/src/imagick_type_gen > /etc/ImageMagick-6/type.xml
      - rm -f imagick_type_gen

      # Install Gems
      - rm -f Gemfile.lock
      - apt install -y libpq-dev postgresql-server-dev-all
      - bundle install --path .bundler

      # Run Tests
      - bundle exec rake

  # docker_latest:
  #   when:
  #     branch: master
  #   image: plugins/docker:latest
  #   username: jmccann
  #   repo: jmccann/sinatra-example
  #   tag: latest
  #   file: Dockerfile
  #   insecure: false
  #
  # docker_tag:
  #   when:
  #     event: tag
  #   image: plugins/docker:latest
  #   username: jmccann
  #   repo: jmccann/sinatra-example
  #   tag: ${DRONE_TAG##v}
  #   file: Dockerfile
  #   insecure: false
